### PR TITLE
fix(Chip): 修复IE浏览器选中样式不正确的bug

### LINKED ISSUE #101: bug(Chip): 在IE11中，Chip选中状态的样式不正确
在IE11中，Chip选中状态时，表示选中的元素位置不正确，没有覆盖chip的图标部分，如下图所示：

image

### PR DESCRIPTION
**Pull request by tianyanqiu**
closed #101

### CODE REVIEW

**Review by liujinxing — APPROVED** [review]

File: src/Chip/Chip.tsx [hunk 1]
```diff
@@ -278,6 +278,7 @@ const selectedStyle = css<ChipLayoutProps>`
 
   > .sinoui-chip--selected__icon {
     position: absolute;
+    top: calc(50% - 12px);
```
Comment (liujinxing) [inline src/Chip/Chip.tsx:281]: 推荐采用通用方案，让元素在垂直方向居中对齐：

```css
top: 50%;
transform: translateY(-50%);
```

见：https://stackoverflow.com/questions/40530101/why-is-translatey-50-needed-to-center-an-element-which-is-at-top-50
